<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Print</title>
	<style type="text/css" media="print">
			body {
				padding: 0 0;
			}
		    @page {
		        margin-top: 0;
		        margin-bottom: 0;
		        background: red; color: red; padding: 60px 0;
		    }
    @page :footer {color: #fff }
    @page :header {color: #fff}
    		        a[href]:after {
        content: none !important;
    }



		    .page_break {
		    	page-break-before: always;
		    }
		    .para_1 {
		    	background: red;
		    }

	</style>
</head>
<body onload="window.print();">
	<div class="para_1">
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
	</div>
	<div class="page_break"></div>
	<div class="para_2">
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
		Lorem, ipsum dolor sit amet consectetur adipisicing elit. Saepe voluptatum dolorum molestias dolore nesciunt ratione officiis tenetur fugiat, dolor architecto. Beatae nulla corrupti quis enim, voluptatem rem laudantium minima, ipsa. Corporis, quam nemo unde, aperiam quos nam incidunt. Possimus a laudantium, voluptatem quaerat sit, fuga earum consequuntur magnam iure magni quae necessitatibus velit, illum iusto asperiores. Porro odio sit voluptatum. Temporibus, eaque amet reprehenderit facilis omnis accusamus, explicabo natus tempora ab, quae quia, velit? Laborum aspernatur, repellendus hic animi deleniti possimus nostrum expedita itaque voluptate, quibusdam vitae, beatae assumenda! Minus autem accusamus labore totam incidunt qui nesciunt odio id beatae.
	</div>
</body>
</html>